parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Baldeweg\Bundle\PdfBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Entity/'
